name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout Go
        uses: actions/checkout@v2

      - name: Build
        run: |
          curl https://raw.githubusercontent.com/go-gilbert/gilbert/master/install.sh | sh
          gilbert run build
